### PR TITLE
Dsd100 12 ap recipe slice

### PR DESCRIPTION
**Pull request by BeKind-Rewind**

### CODE REVIEW

**Comment by bethanyann** [comment]
I'm not sure if this one needs approved or not since the changes were also in the other PR that I approved,but it looks like maybe the package.json changes with the addition of the font awesome packages is still a valid change? 

If this still needs approved please take a look at the merge conflicts which are just from approving the PR that had the RecipeCard and RecipeCard.styles changes in it also.

**Comment by bethanyann** [comment]
Also I noticed that the recipe card hasn't been implemented in the RecipeSearch page yet, which it would need to be to get the recipe props passed into the RecipeCard component. 
RecipeSearch already has a .map() function set up so implementing the RecipeCard and passing in each individual recipe shouldnt be too much additional work!

**Comment by BeKind-Rewind** [comment]
Ok! I’ll look at that. Forgot to stick in on there.  Can I place it on the page like <RecipeCard />? I’ll see if I can get the search to run So I know if I’m doing it right 😭. Maybe I didn’t use a good ingredient (garlic) when I was running it. Amanda ***@***.*** Mar 14, 2023, at 4:06 PM, bethany ann ***@***.***> wrote:﻿
Also I noticed that the recipe card hasn't been implemented in the RecipeSearch page yet, which it would need to be to get the recipe props passed into the RecipeCard component.
RecipeSearch already has a .map() function set up so implementing the RecipeCard and passing in each individual recipe shouldnt be too much additional work!

**Comment by bethanyann** [comment]
Yep, you'll drop in the RecipeCard component like this  ` <RecipeCard recipe={recipe} />`  in the RecipeSearch page, and it will go on line 71 replacing the code that is there now!  Should be pretty easy peasy to implement and this way you'll hopefully be able to search for recipes and see the cards displaying the info on the RecipeSearch page.

image

**Comment by bethanyann** [comment]
I see that you made a new PR to include the RecipeCard in the code instead of adding it to this one, which is ok, but this one still has a lot of merge conflicts so I can't approve it until those are resolved in your branch and then committed again.  

Merge conflicts are the worst so if you need help we can go over it.

**Review by bethanyann — APPROVED** [review]
looks good!

**Pull request merged**
